<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Final project – My projects</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">My projects</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">index</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Final Project.html" aria-current="page"> 
<span class="menu-text">Final Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Data set.html"> 
<span class="menu-text">Data set</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Code-Page.html"> 
<span class="menu-text">Code-Page</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="internal-revenue-service-irs-exempt-organizations-division-factors-and-variables-that-influence-revenue-and-income" class="level1">
<h1>Internal Revenue Service (IRS) Exempt Organizations Division: Factors and variables that influence revenue and income</h1>
<p>by <br> Anand Boldbaatar <br> Veronica Wood</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Tax-exempt organizations are organization that receive federal tax benefits in exchange for providing public services such as charity, education, and healthcare. This study examines how organizational classification and financial characteristics influence revenue, income, and assets among U.S. nonprofit organizations. Data were obtained from the IRS Exempt Organizations Business Master File. Descriptive and regression analyses were conducted to examine patterns in revenue and to identify predictors of high organizational income</p>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<section id="which-organizational-characteristics-most-strongly-predict-whether-a-nonprofit-is-high-income" class="level4">
<h4 class="anchored" data-anchor-id="which-organizational-characteristics-most-strongly-predict-whether-a-nonprofit-is-high-income">Which organizational characteristics most strongly predict whether a nonprofit is high-Income?</h4>
<p>First thing we do is clean the data set and determine which predictors are going to be used. We changed NTEE_code to NTEE_major to make it easier and set up the hypothesis. <br> H₀: Organizational characteristics have no relationship with whether a nonprofit is High-Income. <br> H₁: At least one organizational characteristic is associated with whether a nonprofit is High-Income. The Analysis of Deviance Table shows that ASSET_AMT and REVENUE_AMT are by far the strongest predictors, followed by the organization’s fiscal year-end month (ACCT_PD), NTEE_major, State and Group status. Group status was the only insignificant predictor. we used a generalized linear model with the. To test the accuracy of the model we set up a 80/20 train/test split which had a 0.97 accuracy.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: binomial, link: logit

Response: HighIncome

Terms added sequentially (first to last)

            Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)    
NULL                       267169     370300             
NTEE_major  27     9068    267142     361232   &lt;2e-16 ***
GroupStatus  1        2    267141     361231   0.1978    
STATE       49      857    267092     360374   &lt;2e-16 ***
ACCT_PD      1    18175    267091     342199   &lt;2e-16 ***
ASSET_AMT    1    85183    267090     257015   &lt;2e-16 ***
REVENUE_AMT  1   206144    267089      50871   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      
pred     Low  High
  High   413 26207
  Low  25915   899</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9754463</code></pre>
</div>
</div>
</section>
<section id="random-forest" class="level3">
<h3 class="anchored" data-anchor-id="random-forest">Random forest</h3>
<p>As a comparison we set up random forest model to also test the predictive strength. The results were nearly the same. We also tested the results with Variable importance. As previously established Asset and revenue are the strongest predictors. So we reject the Null hypothesis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       
pred_rf   Low  High
   Low  26294  1019
   High    34 26087</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9802934</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Low       High MeanDecreaseAccuracy MeanDecreaseGini
NTEE_major   15.792944   7.441951            15.352650        942.06111
GroupStatus   1.583322  11.555183             7.171355         64.50143
STATE         1.714387   7.671794             4.967953        970.27806
ACCT_PD      24.847531   3.598103            18.267817       2788.23862
ASSET_AMT    45.826334   7.146857            39.753056      20270.54802
REVENUE_AMT 409.832341 449.456928           447.314524      79929.70270</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<section id="to-what-extent-does-geography-state-level-location-influence-whether-a-nonprofit-is-high-revenue" class="level4">
<h4 class="anchored" data-anchor-id="to-what-extent-does-geography-state-level-location-influence-whether-a-nonprofit-is-high-revenue">To what extent does geography (state-level location) influence whether a nonprofit is high-revenue?</h4>
<p>We used a Logistic Regression model with the state as the sole predictor to determine the direct influence of geography on the likelihood of a non-profit being high-revenue. We make a new column HighRevenue as a binary. We changed the reference state to MT as that was calculated to be the most even probability of being either high or low revenue and set up logistic regression. While financial metrics are the primary driver (as shown in Q1), geography does introduce statistically significant. The data suggests non-profits in the New England area (VT, ME, RI) have a clear advantage in terms of this classification compared to the reference state, while certain Mid-Atlantic or Southern states (NJ, SC) are at a slight disadvantage.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "MT"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     STATEAK     STATEAL     STATEAR     STATEAZ     STATECA 
  1.0000000   1.1601831   0.9847654   0.9417773   1.1809278   0.9770317 
    STATECO     STATECT     STATEDE     STATEFL     STATEGA     STATEHI 
  1.1674272   1.1412791   1.1527778   0.9260783   0.9265980   1.1008264 
    STATEIA     STATEID     STATEIL     STATEIN     STATEKS     STATEKY 
  0.9747706   0.8896648   0.9612230   1.0034065   0.9854577   1.0102459 
    STATELA     STATEMA     STATEMD     STATEME     STATEMI     STATEMN 
  1.0071788   0.8937000   1.0523446   1.3746594   1.0469836   1.0531118 
    STATEMO     STATEMS     STATENC     STATEND     STATENE     STATENH 
  1.1114565   0.8766667   1.2274168   1.2345972   1.0729167   0.9372973 
    STATENJ     STATENM     STATENV     STATENY     STATEOH     STATEOK 
  0.6850978   1.1361816   0.8950472   1.0043860   0.9090722   0.9828259 
    STATEOR     STATEPA     STATERI     STATESC     STATESD     STATETN 
  1.0402178   1.1071368   1.2363281   0.8362709   1.0404624   1.0781722 
    STATETX     STATEUT     STATEVA     STATEVT     STATEWA     STATEWI 
  0.9223468   1.1137931   1.0774318   1.5504949   1.0445398   0.9423005 
    STATEWV     STATEWY 
  1.0443213   1.1717452 </code></pre>
</div>
</div>
</section>
</section>
<section id="queation-3" class="level2">
<h2 class="anchored" data-anchor-id="queation-3">Queation 3</h2>
<section id="which-financial-indicators-most-strongly-distinguish-between-the-largest-nonprofit-mission-types" class="level4">
<h4 class="anchored" data-anchor-id="which-financial-indicators-most-strongly-distinguish-between-the-largest-nonprofit-mission-types">Which financial indicators most strongly distinguish between the largest nonprofit mission types?</h4>
<p>Which financial indicators best distinguish among the five largest NTEE major groups? Do mission groups exhibit consistent financial profiles that align with operational demands and funding models?</p>
<section id="hypotheses" class="level5">
<h5 class="anchored" data-anchor-id="hypotheses">Hypotheses</h5>
<p>H1: Financial characteristics will significantly predict nonprofit mission category. H2: The revenue-to-income ratio will be among the strongest predictors, reflecting operational funding differences across sectors. H3: Education and Arts nonprofits will be associated with higher asset levels. H4: Youth Development, Human Services, and Religion Support organizations will rely more heavily on income rather than revenue.</p>
</section>
<section id="methods" class="level5">
<h5 class="anchored" data-anchor-id="methods">Methods</h5>
<p>Data were obtained from the IRS Business Master File for U.S. tax-exempt organizations. Records with missing values for asset amount, income amount, revenue amount, or revenue-to-income ratio were excluded. The final analytic sample included nonprofits across 27 NTEE major groups, but logistic models were restricted to the five groups with the highest counts: Education (B), Human Services (P), Arts (A), Youth Development (N), and Religion Support (X).</p>
<p>Variables Dependent Variables. We used five binary indicators, each representing whether the organization belonged to a specific NTEE major group (e.g., NTEE_B = 1 if Education, 0 otherwise).</p>
<p>Predictors Variables. Using z-scores we standardized the predictor variables allowing odds ratios to be interpreted relative to a one-standard-deviation change.</p>
<ul>
<li>ASSET_s: Total assets</li>
<li>INCOME_s: Total income</li>
<li>REV_s: Total revenue</li>
<li>RtoI_s: Revenue-to-income ratio</li>
</ul>
</section>
<section id="analytic-strategy" class="level5">
<h5 class="anchored" data-anchor-id="analytic-strategy">Analytic Strategy</h5>
<p>Five separate logistic regression models were estimated:</p>
<p>Odds ratios and 95% Wald confidence intervals were calculated for all predictors.</p>
<p>Given the large sample size, some models produced warnings for probabilities near 0 or 1, which is expected but does not compromise overall interpretability of standardized coefficients.</p>
</section>
<section id="results" class="level5">
<h5 class="anchored" data-anchor-id="results">Results</h5>
<p>A series of standardized logistic regression models were estimated to examine how key financial indicators—assets, income, revenue, and the revenue-to-income ratio—predict membership in the five largest NTEE mission groups: Education (B), Human Services (P), Arts (A), Youth Development (N), and Religion Support (X). The resulting odds ratios and 95% confidence intervals are summarized in Table 2, and coefficient patterns are visualized in Figures 1 and 2.</p>
<p>Across models, assets and income consistently emerged as the strongest predictors of organizational mission type. For Education organizations, higher standardized asset levels were associated with slightly greater odds of being classified under Education (OR = 1.17, CI [1.13, 1.21]), while higher income modestly decreased those odds (OR = 0.93, CI [0.90, 0.96]). This pattern suggests that Education nonprofits tend to hold comparatively large financial positions but do not necessarily operate with unusually high revenue margins.</p>
<p>In contrast, Human Services organizations showed the opposite pattern: asset levels strongly reduced the likelihood of belonging to this group (OR = 0.57, CI [0.50, 0.65]), whereas the revenue-to-income ratio substantially increased the odds (OR = 1.24, CI [1.22, 1.27]). This indicates that Human Services nonprofits typically operate with leaner balance sheets but rely more heavily on converting revenue into operational capacity.</p>
<p>The Arts sector demonstrated a distinct financial profile. Higher asset levels sharply increased the odds of being an Arts organization (OR = 1.47, CI [1.34, 1.61]), while higher revenue substantially reduced those odds (OR = 0.04, CI [0.03, 0.06]). As illustrated in Figures 1 and 2, the Arts sector exhibits the strongest separation between asset dependence and revenue patterns, consistent with many arts organizations relying heavily on endowments, grants, and non-operational funding sources.</p>
<p>Youth Development organizations showed especially strong associations with income: higher income values increased the odds of belonging to this group by more than 2.5 times (OR = 2.56, CI [2.29, 2.85]). Meanwhile, both revenue and assets decreased those odds, suggesting that youth organizations operate with less accumulated wealth but sustained operational funding.</p>
<p>Finally, Religion Support organizations displayed a distinctive financial signature. Higher income levels strongly increased the odds of belonging to this group (OR = 2.72, CI [2.27, 3.27]), while higher revenue sharply decreased those odds (OR = 0.0005, CI [0.0003, 0.0011]). Additionally, a higher revenue-to-income ratio strongly predicted religious classification (OR = 1.42, CI [1.38, 1.46]). As shown in Table 2 and Figures 1–2, Religion Support organizations are financially unique: they show strong reliance on income flows and comparatively low accumulation of revenue relative to income.</p>
<p>Across all five mission types, Figure 1 highlights clear visual divergence in effect sizes, particularly the extremely small revenue odds ratios for Arts, Youth, and Religion. Figure 2 presents an integrated view of confidence intervals and demonstrates that financial indicators reliably differentiate organizational missions. Together, these findings show that even simple financial metrics capture meaningful structural differences between nonprofit mission types.</p>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ntee_results_table.png" class="img-fluid figure-img" width="800"></p>
<figcaption>Odds Ratios and 95% Confidence Intervals Across Top NTEE Groups</figcaption>
</figure>
</div>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Odds Ratios for Financial Predictors Across Top NTEE Groups.jpeg" class="img-fluid figure-img" width="1200"></p>
<figcaption>Odds Ratios for Financial Predictors Across Top NTEE Groups</figcaption>
</figure>
</div>
<p>“How accurately can financial variables predict whether an organization belongs to NTEE Group B (Education), P (Human Services), A (Arts), N (Youth), or X (Religion Support)?”</p>
<p><br></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NTEE_Logistic_Results.png" class="img-fluid figure-img" width="700"></p>
<figcaption>Coeff</figcaption>
</figure>
</div>
</section>
<section id="discussion" class="level5">
<h5 class="anchored" data-anchor-id="discussion">Discussion</h5>
<p>This study examined whether financial characteristics—assets, income, revenue, and revenue-to-income ratios—help distinguish the largest nonprofit mission groups in the NTEE system. Across the five logistic models, financial indicators showed clear and interpretable differences between sectors. As shown in Table 2 and visualized in Figures 1 and 2, each mission type displays a distinct financial pattern.</p>
<p>Assets played a central role for several groups. Education and Arts organizations were more likely to have higher asset levels, suggesting reliance on endowments or long-term capital investments. In contrast, Human Services and Youth nonprofits tended to operate with fewer fixed resources, reflecting their focus on direct service delivery and short-term funding cycles.</p>
<p>Income was especially important for Youth Development and Religion Support organizations. These groups appear to depend more on continuous financial inflows (such as donations or program fees), rather than accumulated assets. Meanwhile, the revenue-to-income ratio strongly distinguished Human Services and Religion Support groups, indicating differences in funding structures or operational efficiency.</p>
<p>While revenue alone was not a strong predictor for most groups—likely due to its wide skew—its standardized form still helped reveal overall financial tendencies. Together, these results show that nonprofit mission categories align with meaningful financial signatures rather than arbitrary labels.</p>
</section>
<section id="conclusion" class="level5">
<h5 class="anchored" data-anchor-id="conclusion">Conclusion</h5>
<p>Overall, the findings indicate that nonprofit mission type can be partially explained by basic financial characteristics. Assets, income, and revenue-to-income ratios consistently differentiated the five largest NTEE groups, demonstrating that financial structure varies systematically across sectors. Education and Arts organizations tend to hold more assets, while Youth and Religion Support organizations rely more on income. Human Services groups show distinctive revenue-to-income behavior, highlighting the financial pressures of service-oriented work.</p>
<p>Although financial data do not capture the full complexity of nonprofit missions, these patterns show that mission type is closely tied to how organizations raise, manage, and rely on financial resources. Future work could expand the analysis by incorporating multi-year financial trends or geographic differences, but the present results already demonstrate that financial indicators offer meaningful insight into the nonprofit landscape.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/username\.github\.io\/repo-name\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>